# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesByParish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=55)),
                ('company_name', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=55)),
                ('owner', models.CharField(max_length=55)),
                ('company_id', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('zipcode', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.AddField(
            model_name='companiesbyparish',
            name='company_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='search.CompanyInfo'),
        ),
        migrations.AddField(
            model_name='companiesbyparish',
            name='parish_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parish', to='search.Parish'),
        ),
        migrations.AddField(
            model_name='companiesbyparish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
